version: '3'
volumes: 
    nextcloud_static:
    db:
services:
    db:
        image: postgres:12.4-alpine
        restart: always
        volumes:
        - db:/var/lib/postgresql/data
        - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
        env_file:
        - ./config/db.env
        command: 
        - -c 
        - config_file=/etc/postgresql/postgresql.conf
    nextcloud:
        image: nextcloud:19.0.1-fpm-alpine
        restart: always
        volumes: 
        - nextcloud_static:/var/www/html
        environment:
        - POSTGRES_HOST=db
        - NEXTCLOUD_ADMIN_USER=gwisp
        - NEXTCLOUD_ADMIN_PASSWORD=qwerty
        env_file:
        - ./config/db.env
        depends_on:
        - db
    web:
        image: nginx:1.19.2-alpine
        restart: always
        ports:
        - '80:80'
        volumes:
        - nextcloud_static:/var/www/html:ro
        - './config/nginx.conf:/etc/nginx/nginx.conf:ro' 
        depends_on: 
        - nextcloud
